<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:macro name="omnibot_body" params="use_sim mecanum">

        <!-- Define robot constants -->
        <xacro:property name="base_width" value="0.561"/>
        <xacro:property name="base_length" value="0.541"/>
        <xacro:property name="base_height" value="0.212"/>

        <xacro:property name="wheel_radius" value="0.07937"/>
        <xacro:property name="wheel_width" value="0.060"/>
        <xacro:property name="wheel_ygap" value="-0.0595"/> 
        <xacro:property name="wheel_zoff" value="${(-base_height/2.0)-0.041}"/>
        <xacro:property name="wheel_xoff" value="-0.15297"/>

        <xacro:property name="caster_xoff" value="0.15297"/>

        <!-- Define intertial property macros  -->
        <xacro:macro name="box_inertia" params="m w h d">
            <inertial>
                <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
                <mass value="${m}"/>
                <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) * (w*w + h*h)}"/>
            </inertial>
        </xacro:macro>

        <xacro:macro name="cylinder_inertia" params="m r h">
            <inertial>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <mass value="${m}"/>
                <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0" iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0" izz="${(m/2) * (r*r)}"/>
            </inertial>
        </xacro:macro>

        <xacro:macro name="sphere_inertia" params="m r">
            <inertial>
                <mass value="${m}"/>
                <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0" iyy="${(2/5) * m * (r*r)}" iyz="0.0" izz="${(2/5) * m * (r*r)}"/>
            </inertial>
        </xacro:macro>

        <!-- Robot Base -->
        <link name="base_link">
            <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="Cyan">
                <color rgba="0 1.0 1.0 1.0"/>
            </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}"/>
                </geometry>
            </collision>
            <xacro:box_inertia m="15" w="${base_width}" d="${base_length}" h="${base_height}"/>
        </link>

        <!-- Robot Footprint -->
        <link name="base_footprint"/>
        <joint name="base_joint" type="fixed">
            <parent link="base_link"/>
            <child link="base_footprint"/>
            <origin xyz="0.0 0.0 ${wheel_zoff-wheel_radius}" rpy="0 0 0"/>
        </joint>

        <!-- Laser -->
        <link name="laser_mount"/>
        <joint name="laser_mount_joint" type="fixed">
            <parent link="base_link"/>
            <child link="laser_mount"/>
            <origin xyz="${base_length/2-0.008} 0.0 ${base_height/2.0}" rpy="0 0 0"/>
        </joint>

        <link name="base_laser">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${0.035/2.0}" length="0.04"/>
                </geometry>
                <material name="Blue">
                    <color rgba="0.0 0.0 1.0 1.0"/>
                </material>
            </visual>
        </link>
        <joint name="laser_joint" type="fixed">
            <parent link="laser_mount"/>
            <child link="base_laser"/>
            <origin xyz="0 0 0.02" rpy="0 0 0"/>
        </joint>

        <!-- IMU -->
        <link name="imu"></link>
        <joint name="imu_joint" type="fixed">
            <parent link="base_link"/>
            <child link="imu"/>
            <origin xyz="-0.2 .1 ${-base_height/2+0.02}" rpy="0 0 0"/>
        </joint>

        <!-- Wheels -->
        <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
            <link name="${prefix}_link">
                <visual>
                    <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                    <geometry>
                        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                    </geometry>
                    <material name="Magenta">
                        <color rgba="1.0 0.0 1.0 1.0"/>
                    </material>
                </visual>
                <collision>
                    <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                    <geometry>
                        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                    </geometry>
                </collision>
                <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>
            </link>

            <joint name="${prefix}_joint" type="continuous">
                <parent link="base_link"/>
                <child link="${prefix}_link"/>
                <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${wheel_zoff}" rpy="0 0 0"/>
                <axis xyz="0 1 0"/>
            </joint>
        </xacro:macro>

        <xacro:wheel prefix="drivewhl_l" x_reflect="1" y_reflect="1" />
        <xacro:wheel prefix="drivewhl_r" x_reflect="1" y_reflect="-1" />

        <!-- Caster Wheels -->
        <xacro:macro name="caster" params="prefix x_reflect y_reflect">
            <link name="${prefix}_link">
                <visual>
                    <geometry>
                        <sphere radius="${wheel_radius}"/>
                    </geometry>
                    <material name="Black">
                        <color rgba="0 0 0 .5"/>
                    </material>
                </visual>
                <collision>
                    <origin xyz="0 0 0" rpy="0 0 0"/>
                    <geometry>
                        <sphere radius="${wheel_radius}"/>
                    </geometry>
                </collision>
                <xacro:sphere_inertia m="0.5" r="${wheel_radius}"/>
            </link>

            <joint name="${prefix}_joint" type="fixed">
                <parent link="base_link"/>
                <child link="${prefix}_link"/>
                <origin xyz="${caster_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${wheel_zoff}" rpy="0 0 0"/>
            </joint>
        </xacro:macro>

        <xacro:caster prefix="caster_l" x_reflect="1" y_reflect="1" />
        <xacro:caster prefix="caster_r" x_reflect="1" y_reflect="-1" />

        <!--Body collider  -->
        <collision>
        <geometry>
            <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        </collision>
        <xacro:box_inertia m="15" w="${base_width}" d="${base_length}" h="${base_height}"/>

    </xacro:macro>

</robot>